WORKSHOP_NAME=lab-k8s-101
WORKSHOP_IMAGE=quay.io/repository/openshiftlabs/lab-k8s-101
CONSOLE_IMAGE=quay.io/openshift/origin-console:4.3
WORKSHOP_TITLE="Kubernetes and OpenShift for JS Developers"
WORKSHOP_DESCRIPTION="A hands-on introduction to Kubernetes and OpenShift for JS Developers"
RESOURCE_BUDGET=large
MAX_SESSION_AGE=9600
IDLE_TIMEOUT=600
SPAWNER_MODE=hosted-workshop
SERVER_LIMIT=100
