WORKSHOP_NAME=lab-k8s-for-js
WORKSHOP_IMAGE=quay.io/repository/openshiftlabs/lab-k8s-for-js
CONSOLE_IMAGE=quay.io/openshift/origin-console:4.2
WORKSHOP_TITLE="Kubernetes and OpenShift for JS Developers"
WORKSHOP_DESCRIPTION="A hands-on introduction to Kubernetes and OpenShift for JS Developers"
RESOURCE_BUDGET=large
MAX_SESSION_AGE=9600
IDLE_TIMEOUT=600
SPAWNER_MODE=hosted-workshop
SERVER_LIMIT=100
